// itgirl/lyrics.js: [start, end, text] for "IT GIRL", timed from word timestamps (whisper) snapped to the 2 s bars.
// 120 BPM, first beat at 0.233 s: beat n = 0.233 + n * 0.5, bar = 2 s.
const LY = [
  [0.2, 4.2, "I-T-G-I-R-L"], [4.25, 8.4, "I-T-G-I-R-L"],
  [8.5, 11.85, "Hate it or love it, the radar is locked"], [11.9, 13.85, "Every move that I make, got the ticker tape blocked"],
  [13.9, 15.85, "Too fly for the chat, too cool for the beef"], [15.9, 17.8, "Got 'em biting their nails down to the teeth"],
  [17.85, 19.65, "Call me buggin', call me bougie, say I act elite"], [19.7, 21.65, "I'm just serving up heavy while you're tasting defeat"],
  [21.7, 23.2, "Talk that talk, yeah you run that jaw"], [23.25, 25.35, "While I'm out here breaking every single rule in the law"],
  [25.4, 27.4, "Got that swagger, got that juice"], [27.45, 29.8, "Loose lips, baby, what's the use?"],
  [29.9, 31.3, "You can plot, you can scheme, throw a little shade"], [31.35, 33.3, "I'm the blueprint, honey, in the shade you made"],
  [33.35, 34.15, "Pump it up, pump it up—"],
  [34.2, 38.25, "I-T-G-I-R-L"], [38.3, 42.35, "I-T-G-I-R-L (it girl)"], [42.4, 43.95, "Yeah, yeah, yeah, I'm that girl... hit 'em!"],
  [43.98, 45.55, "Hit it, drop it, shake it, pop it"], [45.6, 47.95, "Can't stop, won't stop, never gonna drop it!"],
  [48.0, 49.85, "Hit it, drop it, shake it, pop it"], [49.9, 51.9, "Bounce to the bass, hit it right back!"],
  [51.95, 53.75, "Look at it, want it, get it, snap!"], [53.8, 55.9, "Bounce to the bass, hit it right back!"], [55.95, 57.2, "IT GIRL!"],
  [59.45, 61.3, "All that drama? As if! Please stop."], [61.35, 63.3, "Got my hair flipped high, chilling right at the top"],
  [63.35, 65.2, "You're bugging out hard 'cause I don't check the pulse"], [65.25, 67.35, "Living rent-free in your feeds and your thoughts"],
  [67.4, 69.3, "Mad 'cause I'm paid, mad 'cause I'm fly"], [69.35, 71.35, "Catch me rolling on by with a cool little eye"],
  [71.4, 73.4, "Whatever, whatever, you do what you can"], [73.45, 75.5, "Still eating out of the palm of my hand"],
  [75.55, 77.5, "Got that swagger, got that juice"], [77.55, 79.8, "Loose lips, baby, what's the use?"],
  [79.9, 81.3, "You can plot, you can scheme, throw a little shade"], [81.35, 83.3, "I'm the blueprint, honey, in the shade you made"],
  [83.35, 84.2, "Pump it up, pump it up—"],
  [84.25, 88.2, "I-T-G-I-R-L"], [88.25, 91.9, "I-T-G-I-R-L (it girl)"], [91.95, 93.9, "Yeah, yeah, yeah, I'm that girl... hit 'em!"],
  [93.98, 95.55, "Hit it, drop it, shake it, pop it"], [95.6, 97.95, "Can't stop, won't stop, never gonna drop it!"],
  [98.0, 99.85, "Hit it, drop it, shake it, pop it"], [99.9, 101.9, "Bounce to the bass, hit it right back!"],
  [101.95, 103.75, "Look at it, want it, get it, snap!"], [103.8, 105.9, "Bounce to the bass, hit it right back!"], [105.95, 107.2, "IT GIRL!"],
  [109.4, 111.3, "Talk behind my back? That's cute."], [111.35, 113.3, "Keep the rumor mill spinning in a tailored suit."],
  [113.35, 115.4, "You want the aesthetic? You want the lane?"], [115.45, 117.0, "Too bad, honey, you can't duplicate the rain."],
  [117.0, 117.9, "Or the thunder."], [117.95, 122.0, "Yeah, keep talking under your breath."], [123.8, 125.8, "One, two, three—drop!"],
  [125.88, 129.9, "I-T-G-I-R-L"], [129.95, 133.9, "I-T-G-I-R-L"], [133.95, 137.6, "I-T-G-I-R-L (it girl)"], [137.65, 141.25, "Yuh, yuh, yuh — IT GIRL"],
  [141.3, 143.95, "Bounce to the bass, hit it right back!"], [143.98, 145.8, "Look at it, want it, get it, snap!"],
  [145.85, 147.9, "Bounce to the bass, hit it right back!"], [147.95, 149.6, "IT GIRL!"],
  [151.8, 155.8, "I-T-G-I-R-L"], [155.85, 159.9, "I-T-G-I-R-L... IT GIRL"]
];
Object.assign(RU, {
  "I-T-G-I-R-L": "Ай-ти-гёрл", "I-T-G-I-R-L (it girl)": "Ай-ти-гёрл (та самая)", "I-T-G-I-R-L... IT GIRL": "Ай-ти-гёрл… та самая",
  "Hate it or love it, the radar is locked": "Хочешь — злись, хочешь — люби: радар взял цель",
  "Every move that I make, got the ticker tape blocked": "Каждый мой шаг забивает бегущую строку",
  "Too fly for the chat, too cool for the beef": "Слишком крута для чата, выше всех разборок",
  "Got 'em biting their nails down to the teeth": "Они грызут ногти до самых зубов",
  "Call me buggin', call me bougie, say I act elite": "Зови меня странной, зови мажоркой, «строит элиту»",
  "I'm just serving up heavy while you're tasting defeat": "Я просто подаю по-крупному, а ты вкушаешь поражение",
  "Talk that talk, yeah you run that jaw": "Болтай-болтай, работай челюстью",
  "While I'm out here breaking every single rule in the law": "А я тут ломаю каждое правило из кодекса",
  "Got that swagger, got that juice": "У меня есть стиль, у меня есть сок",
  "Loose lips, baby, what's the use?": "Длинный язык, детка, — ну и толку?",
  "You can plot, you can scheme, throw a little shade": "Плети интриги, строй козни, бросай тень",
  "I'm the blueprint, honey, in the shade you made": "Я — оригинал, милый, в твоей же тени",
  "Pump it up, pump it up—": "Громче, громче —",
  "Yeah, yeah, yeah, I'm that girl... hit 'em!": "Да-да-да, я та самая… врежь!",
  "Hit it, drop it, shake it, pop it": "Бей, роняй, тряси, взрывай",
  "Can't stop, won't stop, never gonna drop it!": "Не остановлюсь, не сдамся, никогда не брошу!",
  "Bounce to the bass, hit it right back!": "Прыгай под бас, отвечай ударом!",
  "Look at it, want it, get it, snap!": "Увидела, захотела, взяла — щёлк!",
  "IT GIRL!": "ТА САМАЯ!",
  "All that drama? As if! Please stop.": "Вся эта драма? Ой, да ладно. Хватит.",
  "Got my hair flipped high, chilling right at the top": "Волосы взмахом вверх, отдыхаю на вершине",
  "You're bugging out hard 'cause I don't check the pulse": "Ты бесишься, что я не слежу за пульсом",
  "Living rent-free in your feeds and your thoughts": "Живу бесплатно в твоей ленте и мыслях",
  "Mad 'cause I'm paid, mad 'cause I'm fly": "Злишься, что я при деньгах, злишься, что я летаю",
  "Catch me rolling on by with a cool little eye": "Проезжаю мимо с холодным взглядом",
  "Whatever, whatever, you do what you can": "Как скажешь, как скажешь, делай что можешь",
  "Still eating out of the palm of my hand": "Всё равно ешь с моей ладони",
  "Talk behind my back? That's cute.": "Шепчешься за спиной? Мило.",
  "Keep the rumor mill spinning in a tailored suit.": "Крути мельницу слухов в костюме на заказ.",
  "You want the aesthetic? You want the lane?": "Хочешь мою эстетику? Хочешь мою полосу?",
  "Too bad, honey, you can't duplicate the rain.": "Увы, милый, дождь не скопировать.",
  "Or the thunder.": "И гром тоже.",
  "Yeah, keep talking under your breath.": "Да, продолжай бубнить себе под нос.",
  "One, two, three—drop!": "Раз, два, три — дроп!",
  "Yuh, yuh, yuh — IT GIRL": "Йе, йе, йе — та самая"
});
